[project]
name = "gaze-correction-cam"
version = "0.1.0"
description = ""
authors = [
    {name = "WangWilly",email = "s89667654@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "tensorflow (>=2.19.0,<3.0.0)",
    "dlib (>=19.24.8,<20.0.0)",
    "opencv-python (>=4.11.0.86,<5.0.0.0)",
    "pyobjc (>=11.0,<12.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"

